### PR TITLE
(SIMP-6343) Get default test working

### PR DESCRIPTION
**Pull request by lnemsick-simp**
- Rewrote the default suite to better test SIMP's installation
  prior to the release of SIMP components.
  - Test now installs the assets listed in the Puppetfile.pinned
    via r10k and manual operations.  This includes the building,
    installation, and loading of SIMP's SELinux policy.
  - Test now runs 'simp environment new', 'r10k puppetfile install',
    'simp environment fix', 'simp config' and 'simp bootstrap' to
    bootstrap the SIMP server.
  - The rsyslog forwarding, local login/password change, and LDAP
    login/password change tests have been moved from the
    install_from_tar suite to the default suite so that these
    tests can be run a regular basis.
  - Added a simp cli test that verifies the SIMP server can be
    reconfigured and re-bootstrapped.  It also exercises a few
    test cases for 'simp evironment new'.
  - Added hieradata to allow the vagrant user
    'sudo -r unconfined_r su - root' access after the disa_stig
    compliance profile has been enforced.
- Refactored test code
  - Restructured the code to use shared examples
  - Moved Puppet-related methods from helpers/utils.rb to
    helpers/puppet_helper.rb
- Updated the test suite README.md
- Began updates to other tests suites per the code refactor.
  The rest of the work to get these tests working will be done in
  other (existing) tickets.

KNOWN ISSUES
- Sometimes the rsyslog forwarding tests fail, because of TBD
  rsyslog failures.

### CODE REVIEW

**Comment by lnemsick-simp** [comment]
:heavy_check_mark: https://gitlab.com/simp/simp-core/pipelines/70154992

**Comment by trevor-vaughan** [comment]
Test code looks good. Running the tests against a different test infrastructure just to make sure nothing weird appears.

**Comment by trevor-vaughan** [comment]
Rsyslog test didn't work. Added a `sleep` and trying again.

**Comment by trevor-vaughan** [comment]
Still trying to make this work. Determined that the `/etc/hosts` file on the server was not getting set up properly which was causing it to not send logs to the syslog server.

**Comment by lnemsick-simp** [comment]
The host setup does work in some instances (see linked GitLab pipeline).  So, you may be dealing with a different problem than the intermittent rsyslog forwarding problems I have seen.

**Comment by trevor-vaughan** [comment]
@lnemsick-simp The issue that I'm seeing is repeating consistently at this point. I'm going to go ahead and get the exceptions working and push it but that's proving to be trickier than I expected.

**Comment by trevor-vaughan** [comment]
Narrowed down the `/etc/hosts` issue to a minor bug in `simp config` that particularly conflicts with my test environment. Filed as [SIMP-6843](https://simp-project.atlassian.net/browse/SIMP-6843)

**Comment by trevor-vaughan** [comment]
Added workaround for potentially failing `rsyslog` tests

**Comment by trevor-vaughan** [comment]
:hourglass_flowing_sand: https://gitlab.com/simp/simp-core/pipelines/70844918

**Pull request merged**
