### PR TITLE
(SIMP-2981) Add SIMP-6 Update GPG key

### PR DESCRIPTION
**Pull request by heliocentric**
* Add the SIMP-6 Release update key to the keyring, to be used in the
near future for RPM and git tagged releases and minor updates.

SIMP-2981 #close

### CODE REVIEW

**Comment by jeefberkey** [comment]
Why is this key tied to a specific version of SIMP?

**Comment by heliocentric** [comment]
Conventionally you would use a key per each major release so it is inherently time limited. Typically you update the expire time to match some number of years after our official end of life date.

Unfortunately, we don't have an official EOL date, so we generated a key that expires in 7 years, with the hope that users won't be using SIMP 6 that long and move on to SIMP 7 at some point between then and now.

**Comment by trevor-vaughan** [comment]
@heliocentric Can you rebase please?

**Comment by trevor-vaughan** [comment]
@heliocentric Please make sure the signed key meets your needs and let me know.

**Pull request merged**
