### PR TITLE
(WIP) External Component updates

### PR DESCRIPTION
**Pull request by jeefberkey**
- puppetlabs/motd                 -> 1.7.0
- puppet/yum                      -> 2.1.0
- puppetlabs/mysql                -> 5.2.0
- puppetlabs/java                 -> 2.4.0
- puppetlabs/apache               -> 2.3.0
- puppetlabs/java_ks              -> 2.0.0
- onyxpoint/gpasswd               -> 1.0.4
- puppetlabs/puppet_authorization -> 0.4.0
- puppetlabs/inifile              -> 2.2.0
- puppetlabs/postgresql           -> 5.2.1
- puppetlabs/concat               -> 4.1.1

SIMP-4268 #comment Update several low-effort components
SIMP-3735 #close
SIMP-3737 #close
SIMP-3850 #close
SIMP-3853 #close
SIMP-3903 #close
SIMP-3992 #close
SIMP-3995 #close
SIMP-4245 #close
SIMP-4246 #close
SIMP-4247 #close
SIMP-4248 #close

### CODE REVIEW

**Comment by jeefberkey** [comment]
This probably won't repoclose yet and I expect upgrade issues until SIMP-3895 is done.

**Comment by jeefberkey** [comment]
https://gitlab.com/simp/simp-core/pipelines/16901978

**Comment by lnemsick-simp** [comment]
Marked as WIP becaus of repo closure problems

**Comment by jeefberkey** [comment]
Listed here: https://gist.github.com/jeefberkey/54c7fda78d79e8a2058df858a6ad204a

**Pull request closed without merging**
