### PR TITLE
(SIMP-MAINT) Update to simp-vox_selinux

### PR DESCRIPTION
**Pull request by op-ct**
This updates vox_selinux to include the modifications to fix SIMP-9371

### CODE REVIEW

**Review by lnemsick-simp — CHANGES_REQUESTED** [review]
I believe we want the simp versions of the module, not the tags from VoxPupuli

**Comment by op-ct** [comment]
> I believe we want the simp versions of the module, not the tags from VoxPupuli

@lnemsick-simp why?

**Comment by lnemsick-simp** [comment]
vox_selinux module, not conflicting selinux module.

**Comment by lnemsick-simp** [comment]
We are still waiting for a version that will both build in RHEL8  (no problems with unverrsioned perl script causing autodeps failure) and not require an additional puppet run to ensure the semanage executable is installed for the providers. @trevor-vaughan has been diligently working the issue.  Release of 3.3.2 is pending.  Then, he will convert selinux to vox_selinux and tag for SIMP.

**Comment by lnemsick-simp** [comment]
The issues have been tracked in SIMP's JIRA.

**Comment by op-ct** [comment]
@lnemsick-simp  To be more specific: why would this need a simp- tag instead of using the upstream project's tag, if their release includes our fixes?

We only add `simp-` tags to forks if we need to include commits that haven't been released in the upstream project.projects.

**Comment by lnemsick-simp** [comment]
We use a custom version of the module with the namespace converted from `selinux` to `vox_selinux`.  That version is on the simp-master branch and released with the tag name `simp-x.y.z` to make sure it is distinct from the VoxPupuli tag

**Comment by lnemsick-simp** [comment]
Please see the comment in https://github.com/simp/simp-core/blob/master/Puppetfile.pinned#L469-L475

**Comment by trevor-vaughan** [comment]
Agree with @lnemsick-simp. This should be closed while we wait for the next (fixed) release

**Comment by op-ct** [comment]
Sounds good, thanks!

**Pull request closed without merging**
