### PR TITLE
WIP: (SIMP-7833)(SIMP-7834) Fix Docker images for builds

### PR DESCRIPTION
**Pull request by brandonrdn**
- Fix issue where EL7 doesn't install ACL
- Update last CMD to ENTRYPOINT to automatically switch to build_user on
entry
- Update Gemfile to bump simp_rake_helpers version to 5.11.1

SIMP-7833 #close
SIMP-7834 #close

### CODE REVIEW

**Comment by trevor-vaughan** [comment]
I'm 90% sure that using `ENTRYPOINT` causes issues with different work scenarios and is not required for the usual uses of the images.

**Comment by brandonrdn** [comment]
@trevor-vaughan Yeah, I'm going to be testing this later. I was thinking of the manual steps, so I may be able to add something to the bashrc to fix the rvm issue and just manually su to build_user for the instance of docker build+run. Set it to WIP earlier while testing. The simp_rake_helpers update was already put in a PR by Chris and I didn't notice until I added that here so I have some changes to make.

**Comment by op-ct** [comment]
> I'm 90% sure that using `ENTRYPOINT` causes issues with different work scenarios and is not required for the usual uses of the images.

Agreed: `ENTRYPOINT` _always_ executes the command unless you override it with `--entrypoint`.  This will probably break Beaker/CI, and will certainly irritate folks that just wanted to open a shell.

**Comment by brandonrdn** [comment]
Closing due to partial duplicate MR (simp_rake_helpers version update), and part issue with Dockerfile updates (Works for local builds, but not for CI).

**Pull request closed without merging**
